<?php


namespace app\components;

use danog\MadelineProto\API;
use Yii;
use yii\base\BaseObject;

class Telegram extends BaseObject
{
	public $telephone;
	public $message;

	public function __construct($telephone, $message, $config = [])
	{
		parent::__construct($config);
		$mp = new API('session/session.madeline', Yii::$app->params['api']['tg']);
		$mp->start();

		$this->telephone = $telephone;
		$this->message = $message;
	}

	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
	}

	public function message()
	{
		$mp = new API('session/session.madeline', Yii::$app->params['api']['tg']);
		$mp->start();

		$contact = ['_' => 'inputPhoneContact', 'client_id' => 0, 'phone' => $this->telephone, 'first_name' => '', 'last_name' => ''];
		$import = $mp->contacts->importContacts(['contacts' => [$contact]]);

		if (!empty($import['imported'][0]['user_id'])) {
			$mp->messages->sendMessage(['peer' => $import['imported'][0]['user_id'], 'message' => $this->message]);

			if ($mp->updates->getState()) {
				return Yii::t('ServicesTelegram', 'Сообщение отправленно!'); // TODO-splaandrey: создать категорию для переводом
			} else {
				return Yii::t('ServicesTelegram', 'Ошибка при отправке сообщения!'); // TODO-splaandrey: создать категорию для переводом
			}
		} else {
			return Yii::t('ServicesTelegram', 'Пользователь не найден!'); // TODO-splaandrey: создать категорию для переводом
		}
	}
}